### PR TITLE
Feature branch: Added index.htlm and style.css and deleted linters errors by deleting dependencies

### PR DESCRIPTION
**Pull request by JbirdL86**
In this branch we added:

- Linters
- index.html
- style.css
- Readme.md

### CODE REVIEW

**Comment by Davidosky007** [comment]
Hi, @JbirdL86 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
* I suggest you fix all linter check errors as stated in the project requirements.
* I think you can make your pull request more descriptive, write a short summary of exactly the changes you made. This makes reviewing easy.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by ElijahTobs — APPROVED** [review]
# STATUS: APPROVED ✔️ 🥂 👏 
## Hi @JbirdL86 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by JbirdL86** [comment]
@ElijahTobs I'm not sure why but it's still showing me "Request review" on my progress page. Help me, please!

**Comment by Davidosky007** [comment]
hi @JbirdL86, is it still showing "Request review"?

**Comment by JbirdL86** [comment]
@Davidosky007 it is marke as "complete" now......Thank you!

**Pull request merged**
